openapi: 3.0.0
info:
  title: API for budget application
  description: OpenAPI schema of budget application
  version: 0.1.9
tags:
  - name: hello world sample
paths:
  /hello:
    get:
      summary: Returns a 'hello world' string.
      tags:
        - hello world sample
      description: Returns a 'hello world' string.
      operationId: hello
      responses:
        '200':
          description: A list of user's wallets
          content:
            application/json:
              schema:
                type: string
                example: hello world
  /wallet:
    get:
      summary: Returns  of user's wallets.
      tags:
        - wallet
      description: Returns a list of user's wallets.
      operationId: viewWallets
      responses:
        '200':
          description: A list of user's wallets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/wallet'

components:
    schemas:
      wallet:
        type: object
        properties:
          id:
            type: integer
            format: int64
          balance:
            type: integer
            format: int64
          currency:
            type: string
          is_default:
            type: boolean