/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sandbox.api;

import com.sandbox.model.Wallet;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-07-27T20:53:46.537091800+03:00[Europe/Minsk]")
@Validated
@Tag(name = "wallet", description = "the wallet API")
public interface WalletApi {

    /**
     * GET /wallet : Returns  of user&#39;s wallets.
     * Returns a list of user&#39;s wallets.
     *
     * @return A list of user&#39;s wallets (status code 200)
     */
    @Operation(
        operationId = "viewWallets",
        summary = "Returns  of user's wallets.",
        tags = { "wallet" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of user's wallets", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Wallet.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/wallet",
        produces = { "application/json" }
    )
    ResponseEntity<List<Wallet>> viewWallets(
        
    );

}
